[versions]

velocity = "3.4.0-SNAPSHOT"
libertybans = "1.1.2"

codec4j = "0.2.0-beta.4"

gradle-plugins = "1.6.1"

[libraries]

velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
libertybans = { module = "space.arim.libertybans:bans-api", version.ref = "libertybans" }

codec4j-io-yaml = { module = "dev.siroshun.codec4j:codec4j-io-yaml", version.ref = "codec4j" }

[plugins]

jcommon = { id = "dev.siroshun.gradle.plugins.jcommon", version.ref = "gradle-plugins" }
bundler = { id = "dev.siroshun.gradle.plugins.bundler", version.ref = "gradle-plugins" }
